version: 2
project_name: frieza
builds:
- main: ./cmd/frieza
  env:
    # goreleaser does not work with CGO, it could also complicate
    # usage by users in CI/CD systems like Terraform Cloud where
    # they are unable to install libraries.
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm64
  ignore:
    - goos: windows
      goarch: arm64
    - goos: darwin
      goarch: '386'
    - goos: linux
      goarch: '386'
  binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
- formats: [ 'zip' ]
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
  name_template: "Frieza v{{.Version}}"
  github:
    owner: outscale
    name: frieza
  draft: false
  disable: false
  extra_files:
    - glob: ./docs/README.md