name: pull-request

permissions:
  contents: read

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: ⬇️ Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
    - name: 📦 Build
      run: make build
    - name: 🔎 Lint
      uses: outscale/goutils/.github/actions/lint@b80d2575bc8244821afd5e788df63500bee78146 # main
    - name: 👮 Reuse
      run: make test-reuse
