name: pull-request

permissions:
  contents: read

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: ⬇️ Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version-file: 'go.mod'
    - name: 📦 Build
      run: make build
    - name: 🔎 Lint
      uses: outscale/goutils/.github/actions/lint@main
    - name: 👮 Reuse
      run: make test-reuse
